### ISSUE TITLE
Request curse_of_issyos

### ISSUE THREAD

**Issue by enroag** [m1s3ry/minit-vita#1]
Hi @m1s3ry,
thanks for your amazing work!

This is more a request than an issue... Have you consider porting this game? https://locomalito.com/curse_of_issyos.php
It is a cool game (from the creator of Maldita EX Castilla) and it should play wonderful in the Vita. The game is available to dowload for free.

Best wishes.

**Comment by m1s3ry** [comment]
Hi. Suggestions should be made on my patreon or buy me a coffee. 
I don't know the game, but it looks pretty interesting, and I really like Maldita Castilla. I took a look at the game files and looks to be pretty easy to port. I will ask Locomalito for permission.
